services:

  dialog-kafka:
    image: apache/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"

  dialog-database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dialog
      - POSTGRES_PASSWORD=dialog
      - POSTGRES_DB=dialog
